AbtoTest.MVC/Models/Abstractions/Entity.cs
namespace AbtoTest.MVC.Models.Abstractions;

public abstract class Entity
{
    protected Entity(Guid id)
    {
        Id = id;
    }

    protected Entity()
    {
    }

    public Guid Id { get; set; }
}

AbtoTest.MVC/Models/Children.cs
using AbtoTest.MVC.Models.Abstractions;
using System.Data.SqlClient;

namespace AbtoTest.MVC.Models;

public sealed class Children : Entity
{
    public Children(
        Guid id,
        Guid sponsorId,
        string childNumber, 
        string firstName, 
        string lastName, 
        DateTime birthDate, 
        double pledgeAmount, 
        string photo) 
        : base(id)
    {
        SponsorId = sponsorId;
        ChildNumber = childNumber;
        FirstName = firstName;
        LastName = lastName;
        BirthDate = birthDate;
        PledgeAmount = pledgeAmount;
        Photo = photo;
    }

    public Children()
    {
    }

    public Guid SponsorId { get; set; }

    public string ChildNumber { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public DateTime BirthDate { get; set; }

    public double PledgeAmount { get; set; }

    public string Photo { get; set; }

    public Sponsor? Sponsor { get; set; }
}

AbtoTest.MVC/Models/Sponsor.cs
using AbtoTest.MVC.Models.Abstractions;

namespace AbtoTest.MVC.Models;

public sealed class Sponsor : Entity
{
    public Sponsor(
        Guid id, 
        string firstName, 
        string lastName, 
        string email, 
        DateTime birthDate, 
        string note, 
        List<Children> children) 
        : base(id)
    {
        FirstName = firstName;
        LastName = lastName;
        Email = email;
        BirthDate = birthDate;
        Note = note;
        Children = children;
    }

    public Sponsor()
    {
    }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Email { get; set; }

    public DateTime BirthDate { get; set; }

    public string Note { get; set; }

    public List<Children> Children { get; set; }
}

AbtoTest.MVC/Controllers/SponsorController.cs
using AbtoTest.MVC.Models;
using AbtoTest.MVC.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace AbtoTest.MVC.Controllers;
public class SponsorController : Controller
{
    private readonly ISponsorService _sponsorService;

    public SponsorController(ISponsorService sponsorService)
    {
        _sponsorService = sponsorService;
    }

    [HttpGet]
    public IActionResult Update(Guid id)
    {
        
        Result<Sponsor> result = _sponsorService.GetById(id);

        if (result.IsFailure)
        {
            return NotFound();
        }

        return View(result.Value);
    }

    [HttpPost]
    public IActionResult Update(Sponsor sponsor)
    {
        Result result = _sponsorService.Update(
            sponsor.Id,
            sponsor.FirstName,
            sponsor.LastName,
            sponsor.Email,
            sponsor.BirthDate,
            sponsor.Note);

        if (result.IsFailure)
        {
            return NotFound();
        }

        return View(sponsor);
    }
}

AbtoTest.MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AbtoTest.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AbtoTest.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AbtoTest.MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AbtoTest.MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - AbtoTest.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AbtoTest.MVC/Views/Sponsor/Update.cshtml
@model AbtoTest.MVC.Models.Sponsor

@{
    ViewBag.Title = "title";
}

<h2>Sponsor - @Model.Id</h2>
@using (Html.BeginForm("Update", "Sponsor", FormMethod.Post, new { id = "sponsorForm" }))
{
    <fieldset>
        @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control", placeholder = "Id" } })
        <div class="form">
            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control", placeholder = "First Name" } })
            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control", placeholder = "Last Name" } })
        </div>
        <div class="form">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", placeholder = "Email" } })
            @Html.EditorFor(model => model.BirthDate, new { htmlAttributes = new { @class = "form-control", placeholder = "Birth Date" } })
        </div>
        <div class="form">
            @Html.EditorFor(model => model.Note, new { htmlAttributes = new { @class = "form-control", placeholder = "Note" } })
            <div style="margin-left: 20px;">
                <div>Children:</div>
                @for (var i = 0; i < Model.Children.Count; i++)
                {
                    @Html.HiddenFor(model => model.Children[i].Id)
                    @Html.EditorFor(model => model.Children[i].FirstName, new { htmlAttributes = new { @class = "form-control", placeholder = "Child First Name" } })
                }
            </div>
        </div>
        <button type="button" id="submitBtn" class="btn btn-primary">Submit</button>
    </fieldset>
}

<script src="~/lib/signalr/signalr.js"></script>
@section scripts {
    <script>

        const hubConnection = new signalR.HubConnectionBuilder()
            .withUrl("/update")
            .build();

        hubConnection.on("Notify", function (data) 
        {
            var keyValuePairs = data.split("&");
            var formData = {};

            keyValuePairs.forEach(function (pair) {
                var keyValue = pair.split("=");
                formData[keyValue[0]] = decodeURIComponent(keyValue[1].replace(/\+/g, " "));
            });

            $("#Id").val(formData.Id);
            $("#FirstName").val(formData.FirstName);
            $("#LastName").val(formData.LastName);
            $("#Email").val(formData.Email);
            $("#BirthDate").val(formData.BirthDate);
            $("#Note").val(formData.Note);
        });

        $(function () {
            $("#submitBtn").click(function () {
                $.ajax({
                    url: "@Url.Action("Update", "Sponsor")",
                    type: "POST",
                    data: $("#sponsorForm").serialize(),
                    success: function (response) {
                        alert("Successfully updated");
                    },
                    error: function (xhr, status, error) {
                        alert("Error, cant update");
                    }
                });
            });
        });

        document.getElementById("submitBtn").addEventListener("click", function (e) {
            let formData = $("#sponsorForm").serialize();
            hubConnection.invoke("Notify", formData);
        });

        hubConnection.start();
        
    </script>
}